---
appName: svc-orders
appVersion: {{ version }}

image:
  repository: us-central1-docker.pkg.dev/adelco-corp-commerce-dev/docker-repo-dev/svc-orders
  tag: {{ version }}
  pullPolicy: Always


replicaCount: 1

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

environmentVariables:
  CT_API_URL: "https://api.us-central1.gcp.commercetools.com"
  CT_AUTH_URL: "https://auth.us-central1.gcp.commercetools.com"
  CT_PROJECT_KEY: "adelco-dev"
  GCP_CT_CREDENTIALS_NAME: "CT_CLIENT_ID_ORDERS_SVC"
  GCP_PROJECT: "adelco-corp-commerce-dev"
  ENVIRONMENT: "development"
  SWAGGER_ENV: "dev"
  ROOT_PATH: "orders"
  CARTS_SVC_BASE_URL: "http://service-svc-carts.commerce.svc.cluster.local/carts/v1"
  SEQUENCE_CONTAINER_NAME: "sequence"
  ORDER_NUMBER_KEY: "orderNumber"
  DELIVERY_ZONE_CONTAINER_NAME: "delivery-zone"
  SHIPPING_METHOD_KEY: "default"
  ORDER_STATE_CACHE_TTL: 31536000000
  MONGO_DELIVERIES_SYNC: mongo-deliveries-sync
  ORDER_UPDATED_SYNC: commercetools-orders-updated

livenessProbe:
  livenessProbePath: orders/v1/health/live
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
readinessProbe:
  readinessProbePath: orders/v1/health/ready
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
startupProbe:
  startupProbePath: orders/v1/health/ready
  failureThreshold: 30
  periodSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 216Mi

nodeSelector:
  iam.gke.io/gke-metadata-server-enabled: "true"

affinity: {}

tolerations: []


terminationGracePeriodSeconds: 90

service:
  enabled: true
  name: http-web
  type: ClusterIP
  externalPort: 80
  internalPort: 9376
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: sa-svc-orders@adelco-corp-commerce-dev.iam.gserviceaccount.com
