export default [
  {
    id: 1,
    brandName: 'Proactive',
    name: 'Sabanilla Papel',
    imageUrl: 'https://placehold.co/400',
    price: '$8700',
    calculatedPrice: '$8700',
    unitPrice: '$580',
    unitSize: '8un',
    sellUnit: 'display',
    btnLabelAddToCart: 'Agregar',
    btnLabelSeePrices: 'Ver Precios',
    btnLabelOutOfStock: 'Agotado',
    isInCart: false,
    outOfStock: false,
    slug: 'espiritu-gaucho'
  },
  {
    id: 2,
    brandName: 'Simonds',
    name: 'Protector Solar Crema Spf50',
    imageUrl: 'https://placehold.co/400',
    price: '$6500',
    calculatedPrice: '$6500',
    unitPrice: '$325',
    unitSize: '50g',
    sellUnit: 'display',
    btnLabelAddToCart: 'Agregar',
    btnLabelSeePrices: 'Ver Precios',
    btnLabelOutOfStock: 'Agotado',
    isInCart: false,
    outOfStock: false,
    slug: 'yerba-mate-cruz-de-malta'
  },
  {
    id: 3,
    brandName: 'Yerba Mate Playadito',
    name: 'Yerba Mate con Palos Sabor Intenso Playadito',
    imageUrl:
      'https://images.pexels.com/photos/6624869/pexels-photo-6624869.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    price: '$7500',
    calculatedPrice: '$7500',
    unitPrice: '$500',
    unitSize: '400g',
    sellUnit: 'display',
    btnLabelAddToCart: 'Agregar',
    btnLabelSeePrices: 'Ver Precios',
    btnLabelOutOfStock: 'Agotado',
    isInCart: false,
    outOfStock: false,
    slug: 'yerba-mate-playadito'
  },
  {
    id: 4,
    brandName: 'Yerba Mate Taragüi',
    name: 'Yerba Mate con Palos Sabor Tradicional Taragüi',
    imageUrl:
      'https://images.pexels.com/photos/4195505/pexels-photo-4195505.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    price: '$6900',
    calculatedPrice: '$6900',
    unitPrice: '$460',
    unitSize: '300g',
    sellUnit: 'display',
    btnLabelAddToCart: 'Agregar',
    btnLabelSeePrices: 'Ver Precios',
    btnLabelOutOfStock: 'Agotado',
    isInCart: false,
    outOfStock: false,
    slug: 'yerba-mate-tarangüi'
  },
  {
    id: 5,
    brandName: 'Yerba Mate La Merced',
    name: 'Yerba Mate con Palos Sabor Barbacuá La Merced',
    imageUrl:
      'https://images.pexels.com/photos/4195506/pexels-photo-4195506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    price: '$7800',
    calculatedPrice: '$7800',
    unitPrice: '$390',
    unitSize: '500g',
    sellUnit: 'display',
    btnLabelAddToCart: 'Agregar',
    btnLabelSeePrices: 'Ver Precios',
    btnLabelOutOfStock: 'Agotado',
    isInCart: false,
    outOfStock: false,
    slug: 'yerba-mate-la-merced'
  }
];
